#
# (c) Copyright 2017-2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Nova Database
---
# cells: create and map cell0
- name: nova-post-configure | db_cells | Create and map cell0
  become: yes
  command: >
    {{ nova_api_bin_dir }}/nova-manage
    --config-file {{ nova_api_conf_dir }}/nova.conf
    --config-file {{ nova_api_conf_dir }}/api.conf
    cell_v2 map_cell0
  run_once_per: verb_hosts.NOV_API

# cells: check if cell1 exists
- name: nova-post-configure | db_cells | Check if cell1 exist
  become: yes
  shell: >
    {{ nova_api_bin_dir }}/nova-manage
    --config-file {{ nova_api_conf_dir }}/nova.conf
    --config-file {{ nova_api_conf_dir }}/api.conf
    cell_v2 list_cells 2>/dev/null | grep cell1 | awk '{print $4}'
  run_once_per: verb_hosts.NOV_API
  register: list_cell1_result

# cells: create single cell which will contain all compute hosts
- name: nova-post-configure | db_cells | Create cell1 for compute hosts
  become: yes
  command: >
    {{ nova_api_bin_dir }}/nova-manage
    --config-file {{ nova_api_conf_dir }}/nova.conf
    --config-file {{ nova_api_conf_dir }}/api.conf
    cell_v2 create_cell --name=cell1 --verbose
  run_once_per: verb_hosts.NOV_API
  ignore_errors: True
  when: (list_cell1_result.stdout == "")

# cells: update single cell which will contain all compute hosts
- name: nova-post-configure | db_cells | Update cell1 for compute hosts
  become: yes
  command: >
    {{ nova_api_bin_dir }}/nova-manage
    --config-file {{ nova_api_conf_dir }}/nova.conf
    --config-file {{ nova_api_conf_dir }}/api.conf
    cell_v2 update_cell --cell_uuid {{ list_cell1_result.stdout }}
  run_once_per: verb_hosts.NOV_API
  ignore_errors: True
  when: (list_cell1_result.stdout != "")

# cells: check if cell0 and cell1 exist
- name: nova-post-configure | db_cells | Check if cell0 and cell1 exist
  become: yes
  command: >
    {{ nova_api_bin_dir }}/nova-manage
    --config-file {{ nova_api_conf_dir }}/nova.conf
    --config-file {{ nova_api_conf_dir }}/api.conf
    cell_v2 list_cells
  run_once_per: verb_hosts.NOV_API
  register: list_cells_result
  failed_when: ((list_cells_result.stdout.find("cell0") < 0)
                  or (list_cells_result.stdout.find("cell1") < 0))
