#
# (c) Copyright 2015-2016 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017-2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Configure the nova-api service
---
- include: ../../nova-common/tasks/_set_directories.yml
  vars:
    install_package_result: "{{ ardana_notify_nova_api_install_result }}"

- name: NOV-API | configure | nova-common configure
  include: ../../nova-common/tasks/configure.yml

- name: NOV-API | configure | notify on rootwrap or policy change
  command: /bin/true
  register: ardana_notify_nova_api_restart_required
  when: rootwrap_changed or nova_policy_template_result.changed

- include: ../../nova-common/tasks/_write_conf.yml
  src: "../../NOV-API/templates/api.conf.j2"
  dest: "{{ nova_service_conf_dir }}/api.conf"
  owner: "{{ nova_system_user }}"
  group: "{{ nova_system_group }}"

- name: NOV-API | configure | notify on api.conf change
  command: /bin/true
  register: ardana_notify_nova_api_restart_required
  when: write_conf_result.changed

- name: NOV-API | configure | Apply template
  become: yes
  template:
    src: "{{ item }}.j2"
    dest: "{{ nova_service_conf_dir }}/{{ item }}"
    owner: root
    group: "{{ nova_system_group }}"
    mode: 0640
  with_items:
    - "api-logging.conf"
    - "api_audit_map.conf"
    - "api-paste.ini"
  register: ardana_notify_nova_api_restart_required

- name: NOV-API | configure | Create nova audit logging directory
  become: yes
  file:
    path: "{{ nova_audit_log_location }}"
    owner: "{{ nova_system_user }}"
    group: "{{ nova_system_group | default('root') }}"
    mode: "0755"
    state: directory
  when: nova_api_audit_enable


#
# create modwsgi file for nova-placement-api
#
- name: NOV-API | configure | configure nova-placement-api vhost available
  become: yes
  template:
    src: nova-placement-api-apache2.conf.j2
    dest: "{{ apache2_vhost_dir }}/nova-placement-api-apache2.conf"
    mode: 0644
  register: ardana_notify_nova_placement_api_apache_restart

- name: NOV-API | configure | configure nova-placement-api vhost enabled
  become: yes
  file:
    src: "{{ apache2_vhost_dir }}/nova-placement-api-apache2.conf"
    dest: /etc/apache2/sites-enabled/nova-placement-api-apache2.conf
    state: link
  register: ardana_notify_nova_placement_api_apache_restart
  when: ansible_os_family == 'Debian'

- name: NOV-API | configure | configure nova-placement-api apache file owner
  become: yes
  file:
    path: "{{ log_dir }}/{{ item }}"
    owner: "{{ nova_system_user }}"
    group: "{{ nova_system_group }}"
    mode: 0640
    state: touch
  with_items:
    - nova_placement_api_wsgi.log
    - nova_placement_api_wsgi-access.log

- name: NOV-API | configure | set nova-placement-api log file ownership
  become: yes
  file:
    path: "{{ item }}"
    state: touch
    owner: "{{ nova_system_user }}"
    group: "adm"
    mode: 0640
  with_items:
    - "{{ log_dir }}/nova_placement_api_wsgi.log"
    - "{{ log_dir }}/nova_placement_api_wsgi-access.log"
    - "{{ log_dir }}/nova-placement-api.log"

- name: NOV-API | configure | Create symbolic link for placement-api startup
  become: yes
  file:
    src: "{{ nova_service_bin_dir }}/nova-placement-api"
    dest: "/var/www/nova/nova-placement-api"
    owner: root
    group: "{{ nova_system_group }}"
    state: link

- name: NOV-API | configure | Create Symlinks for api nova.conf from install
  file:
    src: "{{ nova_service_conf_dir }}/{{ item }}"
    dest: "{{ nova_global_conf_dir }}/{{ item }}"
    owner: "{{ nova_system_user }}"
    group: "{{ nova_system_group }}"
    state: link
    mode: 0750
  with_items:
    - nova.conf
  become: yes

- name: NOV-API | configure | Create symbolic link for nova-manage script
  become: yes
  file:
    src: "{{ nova_service_bin_dir }}/nova-manage"
    dest: /usr/local/bin/nova-manage
    owner: root
    group: "{{ nova_system_group }}"
    state: link
    force: yes

- name: NOV-API | configure | Create symbolic link for nova-status script
  become: yes
  file:
    src: "{{ nova_service_bin_dir }}/nova-status"
    dest: /usr/local/bin/nova-status
    owner: root
    group: "{{ nova_system_group }}"
    state: link
    force: yes
