#
# (c) Copyright 2015-2016 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Restart or start the nova-compute service
---
- name: NOV-CMP | start | Activate the latest installed version
  become: yes
  install_package:
    name: nova
    service: nova-compute
    activate: act_on
    version: "{{ ardana_notify_nova_compute_install_result.version }}"
  when: not (ardana_notify_nova_compute_install_result is not defined)

- name: NOV-CMP | start | register persistent fact of activate
  command: /bin/true
  register: ardana_notify_nova_compute_restart_required
  when: ardana_notify_nova_compute_install_result is defined and
        ardana_notify_nova_compute_install_result.changed

- name: NOV-CMP | start | Restart nova-compute service
  become: yes
  service:
    name: nova-compute
    state: restarted
  when: ardana_notify_nova_restart_required.changed or
        (ardana_notify_nova_compute_restart_required is defined and
        ardana_notify_nova_compute_restart_required.changed)

- name: NOV-CMP | start | Ensure nova-compute service started
  become: yes
  service:
    name: nova-compute
    state: started
