#
# (c) Copyright 2017-2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- name: NOV-CMP-KVM | create-compute-secret-key | get keyring value
  become: yes
  shell: >
      grep 'key = ' {{ nova_ses_cinder_keyring_file_path }} | awk '{print $3}'
  register: ses_keyring_value_result

- name: NOV-CMP-KVM | create-compute-secret-key |
    Generate "/etc/ceph/cinder.xml"
  become: yes
  template:
    src: secret.xml.j2
    dest: "/etc/ceph/cinder.xml"
    owner: "root"
    group: "root"
    mode: 0640
  with_items:
    - { uuid: "{{ nova_ses_secret_uuid }}",
        user_name: "{{ nova_ses_user_name }}" }

# libvirtd must be running for the next steps
- name: NOV-CMP-KVM | create-compute-secret-key | start libvirtd
  become: yes
  service:
    name: libvirtd
    state: started

- name: NOV-CMP-KVM | create-compute-secret-key | Define the secret
  become: yes
  command: "virsh secret-define --file /etc/ceph/cinder.xml"

- name: NOV-CMP-KVM | create-compute-secret-key | Set secret value for Nova
  become: yes
  shell: "virsh secret-set-value --secret {{ nova_ses_secret_uuid }} --base64
    {{ ses_keyring_value_result.stdout }}"

- name: NOV-CMP-KVM | create-compute-secret-key |
    Delete the keys from /etc/ceph directory
  become: yes
  file:
    dest: "/etc/ceph/cinder.xml"
    state: absent
  run_once_per: verb_hosts.NOV_CMP
